In [2]:
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [ ]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
print(np.ndim(B))

2


In [7]:
print(B.shape)

(3, 2)


In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([7, 8])
np.dot(A, B)

array([23, 53, 83])

In [9]:
# 簡単なニューラルネットワークの実装

X = np.array([1, 2])
W = np.array([[1, 3, 5], [2, 4, 6]])
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
