In [5]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [ ]:
import numpy as np

"""後で使う関数を入れておくセル"""

def sigmoid(x):
    """シグモイド関数"""
    return 1 / (1 + np.exp(-x))


In [6]:
def softmax(a):
    """ソフトマックス関数のオーバーフローを考慮しない良くない実装"""
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

softmax(np.array([1010, 1000, 990]))

C:\Users\asei\AppData\Local\Temp\ipykernel_9416\2443968948.py:3: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
C:\Users\asei\AppData\Local\Temp\ipykernel_9416\2443968948.py:5: RuntimeWarning: invalid value encountered in divide
  y = exp_a / sum_exp_a


array([nan, nan, nan])

In [8]:
def softmax(a):
    """ソフトマックス関数のオーバーフローを考慮した実装"""
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

softmax(np.array([1010, 1000, 990]))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])